# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1cdf9977b3c7edaf1a50dd5272bf1272"
name = "Dev Announcement Bar"
application_url = "https://localhost:4200"
embedded = true

[build]
dev_store_url = "dev-srore.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_customers"

[auth]
redirect_urls = [
  "https://localhost:4200/auth/callback",
  "https://localhost:4200/auth/tokens",
  "http://127.0.0.1:5173/auth/tokens",
  "http://127.0.0.1:5173/auth/callback",
  "https://96a4-2401-4900-576f-8876-cf5-fa65-2876-2f54.ngrok-free.app/auth/callback",
  "https://96a4-2401-4900-576f-8876-cf5-fa65-2876-2f54.ngrok-free.app/auth/tokens"
]

[webhooks]
api_version = "2025-10"

[pos]
embedded = false
